name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print pwd
        run: pwd
      - name: Print GITHUB_WORKSPACE
        run: echo ${GITHUB_WORKSPACE}
      - name: Are they equal?
        run: '[[ "$(pwd)" == "${GITHUB_WORKSPACE}" ]]'

  build2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foo: [bar, baz]
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: mkdir
        run:  mkdir {{matrix.foo}}
        working-directory: $RUNNER_TEMP
      - name: cd
        run: pwd
        working-directory: $RUNNER_TEMP/{{matrix.foo}}
