name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:18
    steps:
      - uses: actions/checkout@v3
      - name: Print pwd
        run: pwd
      - name: Print GITHUB_WORKSPACE
        run: echo ${GITHUB_WORKSPACE}
      - name: Are they equal?
        run: '[[ "$(pwd)" == "${GITHUB_WORKSPACE}" ]]'

  build2:
    runs-on: ubuntu-latest
    container: 
      image: node:18
    strategy:
      fail-fast: false
      matrix:
        foo: [bar, baz]
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: mkdir
        run:  cd $RUNNER_TEMP; mkdir ${{matrix.foo}}
      - name: cd
        run: cd $RUNNER_TEMP/${{matrix.foo}}; pwd
